# Generated by Django 4.2.16 on 2026-07-22 08:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("schedule", "0012_pdf_uploaded_at"),
    ]

    operations = [
        migrations.AddField(
            model_name="batch",
            name="batch_id",
            field=models.CharField(blank=True, max_length=10, unique=True),
        ),
        migrations.AddField(
            model_name="batch",
            name="number_of_students",
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name="batch",
            name="batch_name",
            field=models.CharField(default="", max_length=255),
        ),
        migrations.AlterField(
            model_name="batch",
            name="courses",
            field=models.ManyToManyField(blank=True, to="schedule.course"),
        ),
        migrations.AlterField(
            model_name="course",
            name="instructors",
            field=models.ManyToManyField(blank=True, to="schedule.instructor"),
        ),
        migrations.AlterField(
            model_name="instructor",
            name="uid",
            field=models.CharField(blank=True, max_length=6, unique=True),
        ),
        migrations.AlterField(
            model_name="pdf",
            name="title",
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name="room",
            name="r_number",
            field=models.CharField(blank=True, max_length=6, unique=True),
        ),
    ]
