# Generated by Django 4.2.16 on 2026-07-22 08:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("schedule", "0013_batch_batch_id_batch_number_of_students_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="course",
            name="max_numb_students",
            field=models.PositiveIntegerField(default=60),
        ),
    ]
